# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('slider_h1', models.CharField(max_length=30)),
                ('slider_h2', models.CharField(max_length=30)),
                ('slider_h3', models.CharField(max_length=30)),
                ('brief_heading', models.CharField(max_length=40)),
                ('brief_body', models.CharField(max_length=450)),
                ('vision_heading', models.CharField(max_length=30)),
                ('vision_body', models.CharField(max_length=150)),
                ('agenda_h1', models.CharField(max_length=50)),
                ('agenda_body1', models.CharField(max_length=255)),
                ('agenda_h2', models.CharField(max_length=50)),
                ('agenda_body2', models.CharField(max_length=255)),
                ('agenda_h3', models.CharField(max_length=50)),
                ('agenda_body3', models.CharField(max_length=255)),
                ('recent_work_h1', models.CharField(max_length=50)),
                ('recent_work_body1', models.CharField(max_length=255)),
                ('recent_work_h2', models.CharField(max_length=50)),
                ('recent_work_body2', models.CharField(max_length=255)),
                ('recent_work_h3', models.CharField(max_length=50)),
                ('recent_work_body3', models.CharField(max_length=255)),
                ('quote_for_the_day', models.CharField(blank=True, max_length=150, null=True)),
                ('slider_image1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('slider_image2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('slider_image3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
