# Generated by Django 2.0.3 on 2018-03-29 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('slider_h1', models.CharField(help_text='Text to displayed on first image.', max_length=100, verbose_name='First Slider Text')),
                ('slider_h2', models.CharField(help_text='Text to displayed on second image.', max_length=100, verbose_name='Second Slider Text')),
                ('slider_h3', models.CharField(help_text='Text to displayed on third image.', max_length=100, verbose_name='Third Slider Text')),
                ('brief_heading', models.CharField(help_text='WPC in 40 characters.', max_length=40, verbose_name='Brief Title')),
                ('brief_body', models.TextField(help_text='WPC in short. First words that a user will read about WPC.', max_length=450, verbose_name='Brief Body')),
                ('vision_heading', models.CharField(max_length=30)),
                ('vision_body', models.TextField(max_length=150)),
                ('agenda_h1', models.CharField(max_length=50)),
                ('agenda_body1', models.TextField(max_length=255)),
                ('agenda_h2', models.CharField(max_length=50)),
                ('agenda_body2', models.TextField(max_length=255)),
                ('agenda_h3', models.CharField(max_length=50)),
                ('agenda_body3', models.TextField(max_length=255)),
                ('agenda_h4', models.CharField(max_length=50)),
                ('agenda_body4', models.TextField(max_length=255)),
                ('featured_works_title', models.CharField(blank=True, help_text='Title to displayed for works section.', max_length=40, null=True)),
                ('featured_blog_title', models.CharField(blank=True, help_text='Title to displayed for blog section.', max_length=40, null=True)),
                ('featured_blog_tagline', models.CharField(help_text='A tagline for blogs.', max_length=200, verbose_name='Blog Tagline')),
                ('quote_for_the_day', models.CharField(blank=True, max_length=150, null=True)),
                ('featured_blog', models.ForeignKey(blank=True, help_text='Will display 3 featured blogs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Blogs Page Link')),
                ('featured_works', models.ForeignKey(blank=True, help_text='Will display 3 featured works.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Works Page Link')),
                ('slider_image1', models.ForeignKey(help_text='First image for the slider.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='First Image')),
                ('slider_image2', models.ForeignKey(help_text='Second image for the slider.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Second Image')),
                ('slider_image3', models.ForeignKey(help_text='Third image for the slider.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Third Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
