# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-30 10:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(help_text='Text to displayed as footer title.', max_length=100, verbose_name='Footer Title')),
                ('f_body', wagtail.core.fields.RichTextField()),
                ('phone_one', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Upto 15 digits allowed.', regex='^\\+?1?\\d{8,15}$')])),
                ('phone_two', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Upto 15 digits allowed.', regex='^\\+?1?\\d{8,15}$')])),
                ('phone_three', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Upto 15 digits allowed.', regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fb_link', models.TextField(blank=True)),
                ('twitter_link', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Footer Text',
            },
        ),
    ]
