# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180930_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='f_title',
            field=models.CharField(help_text='Text to displayed as footer title. Max 50 chars.', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='agenda_body1',
            field=models.TextField(help_text='Max 255 chars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='agenda_body2',
            field=models.TextField(help_text='Max 255 chars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='agenda_body3',
            field=models.TextField(help_text='Max 255 chars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='agenda_body4',
            field=models.TextField(help_text='Max 255 chars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='agenda_h1',
            field=models.CharField(help_text='Max 50 chars.', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='agenda_h2',
            field=models.CharField(help_text='Max 50 chars.', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='agenda_h3',
            field=models.CharField(help_text='Max 50 chars.', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='agenda_h4',
            field=models.CharField(help_text='Max 50 chars.', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brief_body',
            field=models.TextField(help_text='WPC in short. First words that a user will read about WPC. Max 500 chars.', max_length=500, verbose_name='Brief Body'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brief_heading',
            field=models.CharField(help_text='One liner for WPC. Max 50 characters.', max_length=50, verbose_name='Brief Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_blog_tagline',
            field=models.CharField(blank=True, help_text='A tagline for blogs. Max 100 chars.', max_length=200, null=True, verbose_name='Blog Tagline'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_blog_title',
            field=models.CharField(blank=True, help_text='Title to displayed for blog section.Max 50 chars.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_works_title',
            field=models.CharField(blank=True, help_text='Title to displayed for works section. Max 50 chars.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_video_subtitle',
            field=models.CharField(blank=True, help_text='Max 100 chars.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_video_title',
            field=models.CharField(blank=True, help_text='Max 50 chars.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='quote_for_the_day',
            field=models.CharField(default='Some Quote', help_text='Max 500 chars.', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_h1',
            field=models.CharField(help_text='Text to displayed on first image. Max 100 chars.', max_length=100, verbose_name='First Slider Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_h2',
            field=models.CharField(help_text='Text to displayed on second image. Max 100 chars.', max_length=100, verbose_name='Second Slider Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_h3',
            field=models.CharField(help_text='Text to displayed on third image. Max 100 chars.', max_length=100, verbose_name='Third Slider Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_board_body',
            field=models.TextField(blank=True, help_text='Text to displayed just below the social board section. Max 300 chars.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_board_title',
            field=models.CharField(blank=True, help_text='Title to displayed for social board section. Max 50 chars.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_body',
            field=models.TextField(help_text='Max 250 chars.', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_heading',
            field=models.CharField(help_text='Max 50 chars.', max_length=50),
        ),
    ]
