# Generated by Django 3.0.5 on 2020-05-07 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0004_auto_20181007_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='agenda_page1',
            field=models.ForeignKey(blank=True, help_text='Will open up the agenda page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Agenda Page Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='agenda_page2',
            field=models.ForeignKey(blank=True, help_text='Will open up the agenda page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Agenda Page Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='agenda_page3',
            field=models.ForeignKey(blank=True, help_text='Will open up the agenda page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Agenda Page Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='agenda_page4',
            field=models.ForeignKey(blank=True, help_text='Will open up the agenda page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Agenda Page Link'),
        ),
    ]
