# Generated by Django 3.0.5 on 2020-05-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0006_auto_20200509_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='more_about_us',
            field=models.ForeignKey(blank=True, help_text='Will open up the page having details about WPC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='More About US Page Link'),
        ),
    ]
