# Generated by Django 2.0.3 on 2018-07-29 16:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('portfolio_heading', models.CharField(help_text='One liner for all the works. Max 40 characters.', max_length=40, verbose_name='Portfolio Title')),
                ('portfolio_body', models.TextField(help_text='Brief about portfolio.', max_length=450, verbose_name='Portfolio Body')),
                ('header_image', models.ForeignKey(help_text='Image for the header.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Header Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkImagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('preview_heading', models.CharField(help_text='One liner for this work that will be displayed as a heading with preview image. Max 40 characters.', max_length=40, verbose_name='Preview Title')),
                ('work_summary', models.TextField(help_text='A short summary of the work.', max_length=800, verbose_name='Work Summary')),
                ('work_date', models.DateField(blank=True, help_text='Date/Start date of the work.', null=True, verbose_name='Date')),
                ('work_video_title', models.CharField(blank=True, max_length=30, null=True)),
                ('work_video_subtitle', models.CharField(blank=True, max_length=60, null=True)),
                ('work_video_url', models.URLField(blank=True, help_text='Paste the video embed url from youtube.', null=True, verbose_name='Video URL')),
                ('work_desc', wagtail.core.fields.RichTextField(help_text='A complete description of the work.', verbose_name='Work Description')),
                ('preview_image', models.ForeignKey(help_text='Image for the preview.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Preview Image')),
                ('work_video_image', models.ForeignKey(blank=True, help_text='Screenshot image of the video', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Video screenshot/image.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='portfolio.WorkImagePage'),
        ),
    ]
