# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioindexpage',
            name='portfolio_body',
            field=models.TextField(help_text='Brief about portfolio. Max 500 chars.', max_length=500, verbose_name='Portfolio Body'),
        ),
        migrations.AlterField(
            model_name='portfolioindexpage',
            name='portfolio_heading',
            field=models.CharField(help_text='One liner for all the works. Max 50 chars.', max_length=50, verbose_name='Portfolio Title'),
        ),
        migrations.AlterField(
            model_name='workimagepage',
            name='preview_heading',
            field=models.CharField(help_text='One liner for this work that will be displayed as a heading with preview image. Max 50 characters.', max_length=50, verbose_name='Preview Title'),
        ),
        migrations.AlterField(
            model_name='workimagepage',
            name='work_summary',
            field=models.TextField(help_text='A short summary of the work. Max 800 chars.', max_length=800, verbose_name='Work Summary'),
        ),
        migrations.AlterField(
            model_name='workimagepage',
            name='work_video_subtitle',
            field=models.CharField(blank=True, help_text='Max 100 chars.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workimagepage',
            name='work_video_title',
            field=models.CharField(blank=True, help_text='Max 50 chars.', max_length=50, null=True),
        ),
    ]
