# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.CharField(blank=True, help_text='Description for the category. Max 500 chars.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(help_text='Max 80 chars.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'hr', 'ol', 'ul', 'link', 'document-link'], icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/embed_block.html'))], blank=True, verbose_name='Page body'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Max 255 chars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(help_text='Max 254 chars.', max_length=254, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='people',
            name='job_title',
            field=models.CharField(help_text='Max 254 chars.', max_length=254, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(help_text='Max 254 chars.', max_length=254, verbose_name='Last name'),
        ),
    ]
