# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='intro',
            field=models.CharField(blank=True, help_text='A small intro about the organization. Max 300 chars.', max_length=300, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Max 100 chars.', max_length=100, verbose_name='Org Name'),
        ),
    ]
